### login
POST http://localhost:8000/auth/register
Content-Type: application/json


{
    "email": "xlzthiago@gmail.com",
    "password":"123456"
}



### registrar


POST http://localhost:8000/auth/register
Content-Type: application/json


{
    "username": "tiago",
    "email": "xlzthiago@gmail.com",
    "password":"123456"
}
