@BASE=http://localhost:8000



### login
POST {{BASE}}/auth/login
Content-Type: application/json


{
    "email": "xlzthiago@gmail.com",
    "password":"123456"
}


### register
POST {{BASE}}/auth/register
Content-Type: application/json


{
    "username": "tiago",
    "email": "xlzthiago@gmail.com",
    "password":"123456"
}
